export const orderFlowFacetAbi = [
	{
		inputs: [
			{ internalType: "uint256", name: "circleId", type: "uint256" },
			{ internalType: "uint256", name: "assignUpto", type: "uint256" },
			{ internalType: "bytes32", name: "currency", type: "bytes32" },
			{ internalType: "address", name: "user", type: "address" },
			{ internalType: "uint256", name: "usdtAmount", type: "uint256" },
			{ internalType: "uint256", name: "fiatAmount", type: "uint256" },
			{ internalType: "int256", name: "orderType", type: "int256" },
			{ internalType: "uint256", name: "preferredPCConfigId", type: "uint256" },
		],
		name: "getAssignableMerchantsFromCircle",
		outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "address", name: "_user", type: "address" },
			{ internalType: "bytes32", name: "_nativeCurrency", type: "bytes32" },
		],
		name: "userTxLimit",
		outputs: [
			{ internalType: "uint256", name: "", type: "uint256" },
			{ internalType: "uint256", name: "", type: "uint256" },
		],
		stateMutability: "view",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "string", name: "_pubKey", type: "string" },
			{ internalType: "uint256", name: "_amount", type: "uint256" },
			{ internalType: "address", name: "_recipientAddr", type: "address" },
			{ internalType: "uint8", name: "_orderType", type: "uint8" },
			{ internalType: "string", name: "_userUpi", type: "string" },
			{ internalType: "string", name: "_userPubKey", type: "string" },
			{ internalType: "bytes32", name: "_currency", type: "bytes32" },
			{ internalType: "uint256", name: "preferredPaymentChannelConfigId", type: "uint256" },
			{ internalType: "uint256", name: "_circleId", type: "uint256" },
			{ internalType: "uint256", name: "_fiatAmountLimit", type: "uint256" },
		],
		name: "placeOrder",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [{ internalType: "uint256", name: "_orderId", type: "uint256" }],
		name: "cancelOrder",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		inputs: [
			{ internalType: "uint256", name: "_orderId", type: "uint256" },
			{ internalType: "string", name: "_userEncUpi", type: "string" },
			{ internalType: "uint256", name: "_updatedAmount", type: "uint256" },
		],
		name: "setSellOrderUpi",
		outputs: [],
		stateMutability: "nonpayable",
		type: "function",
	},
	{
		type: "event",
		name: "OrderPlaced",
		anonymous: false,
		inputs: [
			{ indexed: true, name: "orderId", type: "uint256" },
			{ indexed: true, name: "user", type: "address" },
			{ indexed: true, name: "merchant", type: "address" },
			{ indexed: false, name: "amount", type: "uint256" },
			{ indexed: false, name: "orderType", type: "uint8" },
			{ indexed: false, name: "placedTimestamp", type: "uint256" },
			{
				indexed: false,
				name: "_order",
				type: "tuple",
				components: [
					{ name: "amount", type: "uint256" },
					{ name: "fiatAmount", type: "uint256" },
					{ name: "placedTimestamp", type: "uint256" },
					{ name: "completedTimestamp", type: "uint256" },
					{ name: "userCompletedTimestamp", type: "uint256" },
					{ name: "acceptedMerchant", type: "address" },
					{ name: "user", type: "address" },
					{ name: "recipientAddr", type: "address" },
					{ name: "pubkey", type: "string" },
					{ name: "encUpi", type: "string" },
					{ name: "userCompleted", type: "bool" },
					{ name: "status", type: "uint8" },
					{ name: "orderType", type: "uint8" },
					{
						name: "disputeInfo",
						type: "tuple",
						components: [
							{ name: "raisedBy", type: "uint8" },
							{ name: "status", type: "uint8" },
							{ name: "redactTransId", type: "uint256" },
							{ name: "accountNumber", type: "uint256" },
						],
					},
					{ name: "id", type: "uint256" },
					{ name: "userPubKey", type: "string" },
					{ name: "encMerchantUpi", type: "string" },
					{ name: "acceptedAccountNo", type: "uint256" },
					{ name: "assignedAccountNos", type: "uint256[]" },
					{ name: "currency", type: "bytes32" },
					{ name: "preferredPaymentChannelConfigId", type: "uint256" },
					{ name: "circleId", type: "uint256" },
				],
			},
		],
	},
	{
		type: "event",
		name: "OrderAccepted",
		anonymous: false,
		inputs: [
			{ indexed: true, name: "orderId", type: "uint256" },
			{ indexed: true, name: "merchant", type: "address" },
			{ indexed: false, name: "pubKey", type: "string" },
			{
				indexed: false,
				name: "_order",
				type: "tuple",
				components: [
					{ name: "amount", type: "uint256" },
					{ name: "fiatAmount", type: "uint256" },
					{ name: "placedTimestamp", type: "uint256" },
					{ name: "completedTimestamp", type: "uint256" },
					{ name: "userCompletedTimestamp", type: "uint256" },
					{ name: "acceptedMerchant", type: "address" },
					{ name: "user", type: "address" },
					{ name: "recipientAddr", type: "address" },
					{ name: "pubkey", type: "string" },
					{ name: "encUpi", type: "string" },
					{ name: "userCompleted", type: "bool" },
					{ name: "status", type: "uint8" },
					{ name: "orderType", type: "uint8" },
					{
						name: "disputeInfo",
						type: "tuple",
						components: [
							{ name: "raisedBy", type: "uint8" },
							{ name: "status", type: "uint8" },
							{ name: "redactTransId", type: "uint256" },
							{ name: "accountNumber", type: "uint256" },
						],
					},
					{ name: "id", type: "uint256" },
					{ name: "userPubKey", type: "string" },
					{ name: "encMerchantUpi", type: "string" },
					{ name: "acceptedAccountNo", type: "uint256" },
					{ name: "assignedAccountNos", type: "uint256[]" },
					{ name: "currency", type: "bytes32" },
					{ name: "preferredPaymentChannelConfigId", type: "uint256" },
					{ name: "circleId", type: "uint256" },
				],
			},
		],
	},
	{
		type: "event",
		name: "BuyOrderPaid",
		anonymous: false,
		inputs: [
			{ indexed: true, name: "orderId", type: "uint256" },
			{ indexed: true, name: "user", type: "address" },
			{
				indexed: false,
				name: "_order",
				type: "tuple",
				components: [
					{ name: "amount", type: "uint256" },
					{ name: "fiatAmount", type: "uint256" },
					{ name: "placedTimestamp", type: "uint256" },
					{ name: "completedTimestamp", type: "uint256" },
					{ name: "userCompletedTimestamp", type: "uint256" },
					{ name: "acceptedMerchant", type: "address" },
					{ name: "user", type: "address" },
					{ name: "recipientAddr", type: "address" },
					{ name: "pubkey", type: "string" },
					{ name: "encUpi", type: "string" },
					{ name: "userCompleted", type: "bool" },
					{ name: "status", type: "uint8" },
					{ name: "orderType", type: "uint8" },
					{
						name: "disputeInfo",
						type: "tuple",
						components: [
							{ name: "raisedBy", type: "uint8" },
							{ name: "status", type: "uint8" },
							{ name: "redactTransId", type: "uint256" },
							{ name: "accountNumber", type: "uint256" },
						],
					},
					{ name: "id", type: "uint256" },
					{ name: "userPubKey", type: "string" },
					{ name: "encMerchantUpi", type: "string" },
					{ name: "acceptedAccountNo", type: "uint256" },
					{ name: "assignedAccountNos", type: "uint256[]" },
					{ name: "currency", type: "bytes32" },
					{ name: "preferredPaymentChannelConfigId", type: "uint256" },
					{ name: "circleId", type: "uint256" },
				],
			},
		],
	},
	{
		type: "event",
		name: "OrderCompleted",
		anonymous: false,
		inputs: [
			{ indexed: true, name: "orderId", type: "uint256" },
			{ indexed: true, name: "user", type: "address" },
			{ indexed: false, name: "completedTimestamp", type: "uint256" },
			{
				indexed: false,
				name: "_order",
				type: "tuple",
				components: [
					{ name: "amount", type: "uint256" },
					{ name: "fiatAmount", type: "uint256" },
					{ name: "placedTimestamp", type: "uint256" },
					{ name: "completedTimestamp", type: "uint256" },
					{ name: "userCompletedTimestamp", type: "uint256" },
					{ name: "acceptedMerchant", type: "address" },
					{ name: "user", type: "address" },
					{ name: "recipientAddr", type: "address" },
					{ name: "pubkey", type: "string" },
					{ name: "encUpi", type: "string" },
					{ name: "userCompleted", type: "bool" },
					{ name: "status", type: "uint8" },
					{ name: "orderType", type: "uint8" },
					{
						name: "disputeInfo",
						type: "tuple",
						components: [
							{ name: "raisedBy", type: "uint8" },
							{ name: "status", type: "uint8" },
							{ name: "redactTransId", type: "uint256" },
							{ name: "accountNumber", type: "uint256" },
						],
					},
					{ name: "id", type: "uint256" },
					{ name: "userPubKey", type: "string" },
					{ name: "encMerchantUpi", type: "string" },
					{ name: "acceptedAccountNo", type: "uint256" },
					{ name: "assignedAccountNos", type: "uint256[]" },
					{ name: "currency", type: "bytes32" },
					{ name: "preferredPaymentChannelConfigId", type: "uint256" },
					{ name: "circleId", type: "uint256" },
				],
			},
		],
	},
	{
		type: "event",
		name: "CancelledOrders",
		anonymous: false,
		inputs: [
			{ indexed: true, name: "orderId", type: "uint256" },
			{
				indexed: false,
				name: "_order",
				type: "tuple",
				components: [
					{ name: "amount", type: "uint256" },
					{ name: "fiatAmount", type: "uint256" },
					{ name: "placedTimestamp", type: "uint256" },
					{ name: "completedTimestamp", type: "uint256" },
					{ name: "userCompletedTimestamp", type: "uint256" },
					{ name: "acceptedMerchant", type: "address" },
					{ name: "user", type: "address" },
					{ name: "recipientAddr", type: "address" },
					{ name: "pubkey", type: "string" },
					{ name: "encUpi", type: "string" },
					{ name: "userCompleted", type: "bool" },
					{ name: "status", type: "uint8" },
					{ name: "orderType", type: "uint8" },
					{
						name: "disputeInfo",
						type: "tuple",
						components: [
							{ name: "raisedBy", type: "uint8" },
							{ name: "status", type: "uint8" },
							{ name: "redactTransId", type: "uint256" },
							{ name: "accountNumber", type: "uint256" },
						],
					},
					{ name: "id", type: "uint256" },
					{ name: "userPubKey", type: "string" },
					{ name: "encMerchantUpi", type: "string" },
					{ name: "acceptedAccountNo", type: "uint256" },
					{ name: "assignedAccountNos", type: "uint256[]" },
					{ name: "currency", type: "bytes32" },
					{ name: "preferredPaymentChannelConfigId", type: "uint256" },
					{ name: "circleId", type: "uint256" },
				],
			},
		],
	},
] as const;
